//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViliborService1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices.lb.lt/VilibidVilibor", ConfigurationName="ViliborService1.VilibidViliborSoap")]
    public interface VilibidViliborSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.lb.lt/VilibidVilibor/getVilibRateTypes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> getVilibRateTypesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.lb.lt/VilibidVilibor/getLatestVilibRate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<decimal> getLatestVilibRateAsync(string RateType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.lb.lt/VilibidVilibor/getVilibRate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<decimal> getVilibRateAsync(string RateType, string Date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.lb.lt/VilibidVilibor/getVilibRatesByDate_XmlString", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> getVilibRatesByDate_XmlStringAsync(string Date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.lb.lt/VilibidVilibor/getVilibRatesByRateType_XmlString", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> getVilibRatesByRateType_XmlStringAsync(string RateType, string DateLow, string DateHigh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.lb.lt/VilibidVilibor/getVilibRatesByDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> getVilibRatesByDateAsync(string Date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://webservices.lb.lt/VilibidVilibor/getVilibRatesByRateType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> getVilibRatesByRateTypeAsync(string RateType, string DateLow, string DateHigh);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public interface VilibidViliborSoapChannel : ViliborService1.VilibidViliborSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.0")]
    public partial class VilibidViliborSoapClient : System.ServiceModel.ClientBase<ViliborService1.VilibidViliborSoap>, ViliborService1.VilibidViliborSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public VilibidViliborSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(VilibidViliborSoapClient.GetBindingForEndpoint(endpointConfiguration), VilibidViliborSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VilibidViliborSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(VilibidViliborSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VilibidViliborSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(VilibidViliborSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VilibidViliborSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> getVilibRateTypesAsync()
        {
            return base.Channel.getVilibRateTypesAsync();
        }
        
        public System.Threading.Tasks.Task<decimal> getLatestVilibRateAsync(string RateType)
        {
            return base.Channel.getLatestVilibRateAsync(RateType);
        }
        
        public System.Threading.Tasks.Task<decimal> getVilibRateAsync(string RateType, string Date)
        {
            return base.Channel.getVilibRateAsync(RateType, Date);
        }
        
        public System.Threading.Tasks.Task<string> getVilibRatesByDate_XmlStringAsync(string Date)
        {
            return base.Channel.getVilibRatesByDate_XmlStringAsync(Date);
        }
        
        public System.Threading.Tasks.Task<string> getVilibRatesByRateType_XmlStringAsync(string RateType, string DateLow, string DateHigh)
        {
            return base.Channel.getVilibRatesByRateType_XmlStringAsync(RateType, DateLow, DateHigh);
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> getVilibRatesByDateAsync(string Date)
        {
            return base.Channel.getVilibRatesByDateAsync(Date);
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> getVilibRatesByRateTypeAsync(string RateType, string DateLow, string DateHigh)
        {
            return base.Channel.getVilibRatesByRateTypeAsync(RateType, DateLow, DateHigh);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.VilibidViliborSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.VilibidViliborSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.VilibidViliborSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://old.lb.lt/webservices/VilibidVilibor/VilibidVilibor.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.VilibidViliborSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://old.lb.lt/webservices/VilibidVilibor/VilibidVilibor.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            VilibidViliborSoap,
            
            VilibidViliborSoap12,
        }
    }
}
